# Generated by Django 4.2.11 on 2024-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('offensive_content', 'Offensive Content'), ('foul_language', 'Foul Language'), ('other', 'Other')], default='offensive_content', max_length=32),
        ),
    ]
